[package]
name = "code2prompt-python"
version = "4.3.0"
authors = [
    "Olivier D'Ancona <olivier_dancona@hotmail.com>",
    "Mufeed VH <contact@mufeedvh.com>",
]
description = "Native Python bindings for code2prompt"
homepage = "https://code2prompt.dev"
documentation = "https://code2prompt.dev/docs/welcome"
repository = "https://github.com/mufeedvh/code2prompt"
license = "MIT"
edition = "2024"
readme = "README.md"

[lib]
name = "code2prompt_rs"
crate-type = ["cdylib"]

[dependencies]
code2prompt_core = { path = "../code2prompt-core" }
pyo3 = { workspace = true }
