name: Rust CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: 
          - "x86_64-unknown-linux-gnu"
          - "x86_64-apple-darwin"
          - "aarch64-apple-darwin"
          - "x86_64-pc-windows-gnu"
          - "aarch64-unknown-linux-gnu"
    steps:
      - uses: actions/checkout@v4

      - name: Configure Rust toolchain for ${{ matrix.target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.target }}

      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload binary for ${{ matrix.target }}
        uses: actions/upload-artifact@v3
        with:
          name: binary-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/code2prompt
